apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-rolebinding
  namespace: autoscaler-controller-system
subjects:
  - kind: ServiceAccount
    name: autoscaler-sa
    namespace: autoscaler-controller-system
roleRef:
  kind: Role
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io