apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest # Replace with your hello-world webserver image
        ports:
        - containerPort: 80
      - name: metrics-collector
        image: lohmat/sidecar:latest
        env:
        - name: API_URL
          value: "http://api-service:8080/metrics" # API endpoint to send metrics
