apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-deployment
  namespace: autoscaler-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      containers:
        - name: autoscaler-container
          image: autoscaler:v0.4
          ports:
            - containerPort: 8080
          env:
            - name: KUBECONFIG
              value: ""
            - name: NAMESPACE
              value: "autoscaler-controller-system"
            - name: DEPLOYMENT
              value: "app-deployment"
            - name: SERVICE
              value: "app-service"
            - name: TARGET_PORT
              value: "8081"
            - name: IDLE_TIME
              value: "30s"
