apiVersion: v1
kind: Service
metadata:
  name: autoscaler-service
  namespace: autoscaler-controller-system
spec:
  type: NodePort
  selector:
    app: autoscaler
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8080
