apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: autoscaler-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: nginx  # Простое приложение
          ports:
            - containerPort: 80
            - containerPort: 443