apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: autoscaler-controller-system
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 80
    - protocol: TCP
      name: https
      port: 8082
      targetPort: 443