apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  namespace: autoscaler-controller-system
spec:
  selector:
    app: fibonacci
  ports:
    - protocol: TCP
      name: http
      port: 5001
      targetPort: 5000