# permissions for end users to edit customautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autoscaler-controller
    app.kubernetes.io/managed-by: kustomize
  name: customautoscaler-editor-role
rules:
- apiGroups:
  - autoscaler-group.autoscaler
  resources:
  - customautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler-group.autoscaler
  resources:
  - customautoscalers/status
  verbs:
  - get
